// Code generated by hertz generator.

package wcd_manage

import (
	"bytes"
	"context"
	"fmt"
	"github.com/DeepLangAI/wcd/biz/model/wcd_manage"
	"github.com/DeepLangAI/wcd/service/manage"
	"github.com/bytedance/sonic"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// SiteRuleList .
// @router /api/v1/site_rule/list [POST]
func SiteRuleList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req wcd_manage.SiteRuleListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	s := manage.NewRuleManageService(ctx)
	list, err := s.List(req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	resp := new(wcd_manage.SiteRuleListResp)
	resp.Data = list

	c.JSON(consts.StatusOK, resp)
}

// SiteRuleDetail .
// @router /api/v1/site_rule/detail [POST]
func SiteRuleDetail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req wcd_manage.SiteRuleDetailReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	s := manage.NewRuleManageService(ctx)
	detail, err := s.Detail(req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	resp := new(wcd_manage.SiteRuleDetailResp)
	resp.Data = detail

	c.JSON(consts.StatusOK, resp)
}

// CreateSiteRule .
// @router /api/v1/site_rule/testing/new [POST]
func CreateSiteRule(ctx context.Context, c *app.RequestContext) {
	var err error
	var req wcd_manage.CreateSiteRuleReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	s := manage.NewRuleManageService(ctx)
	rule, err := s.NewTestingRule(req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	resp := new(wcd_manage.CreateSiteRuleResp)
	resp.Data = rule

	c.JSON(consts.StatusOK, resp)
}

// CreateSiteRuleFromProd .
// @router /api/v1/site_rule/prod/to_test [POST]
func CreateSiteRuleFromProd(ctx context.Context, c *app.RequestContext) {
	var err error
	var req wcd_manage.ExportProdRuleToTestReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	s := manage.NewRuleManageService(ctx)
	rule, err := s.ProdToTest(req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	resp := new(wcd_manage.ExportProdRuleToTestResp)
	resp.Data = rule

	c.JSON(consts.StatusOK, resp)
}

// PublishSiteRule .
// @router /api/v1/site_rule/testing/publish [POST]
func PublishSiteRule(ctx context.Context, c *app.RequestContext) {
	var err error
	var req wcd_manage.PublishSiteRuleReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	s := manage.NewRuleManageService(ctx)
	err = s.Publish(req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	resp := new(wcd_manage.PublishSiteRuleResp)

	c.JSON(consts.StatusOK, resp)
}

// DeleteSiteRule .
// @router /api/v1/site_rule/delete [POST]
func DeleteSiteRule(ctx context.Context, c *app.RequestContext) {
	var err error
	var req wcd_manage.DeleteSiteRuleReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	s := manage.NewRuleManageService(ctx)
	err = s.Delete(req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	resp := new(wcd_manage.DeleteSiteRuleResp)

	c.JSON(consts.StatusOK, resp)
}

// UpdateSiteRule .
// @router /api/v1/site_rule/testing/update [POST]
func UpdateSiteRule(ctx context.Context, c *app.RequestContext) {
	var err error
	var req wcd_manage.SiteRuleData
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	s := manage.NewRuleManageService(ctx)
	err = s.Update(req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	resp := new(wcd_manage.UpdateSiteRuleResp)

	c.JSON(consts.StatusOK, resp)
}

// ExportSiteRules .
// @router /api/v1/site_rule/export [POST]
func ExportSiteRules(ctx context.Context, c *app.RequestContext) {
	var err error
	var req wcd_manage.EmptyReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	s := manage.NewRuleManageService(ctx)
	export, err := s.Export(req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	marshal, err := sonic.Marshal(export)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	buffer := bytes.NewBuffer(marshal)
	fileName := fmt.Sprintf("rules_%v.json", time.Now().Format("2006-01-02T15:04:05"))

	c.Response.Header.Add("Content-Type", "text/html; charset=UTF-8")
	c.Response.Header.Add("Content-Type", "application/octet-stream")
	c.Response.Header.Add("Content-Disposition", "attachment; filename="+fileName)
	c.Response.Header.Add("Access-Control-Expose-Headers", "Content-Disposition")
	// 文件写入body
	c.Response.BodyWriter().Write(buffer.Bytes())
}

// ImportSiteRules .
// @router /api/v1/site_rule/import [POST]
func ImportSiteRules(ctx context.Context, c *app.RequestContext) {
	var err error
	var req wcd_manage.EmptyReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	s := manage.NewRuleManageService(ctx)
	err = s.ImportFromCtx(c)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
	}
	resp := new(wcd_manage.ImportSiteRulesResp)

	c.JSON(consts.StatusOK, resp)
}
