// Code generated by hertz generator.

package wcd

import (
	"github.com/DeepLangAI/go_lib/middleware"
	"github.com/DeepLangAI/wcd/consts"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.TraceServerMiddleware(),
		middleware.ReqRespLogMiddleware(),
		middleware.ResponseVersionServerMiddleware(consts.VERSION),
	}

}

func _baseparseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _wcdMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _distillMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _wcdparseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _segmentMw() []app.HandlerFunc {
	// your code...
	return nil
}
