// Code generated by hertz generator.

package wcd

import (
	"context"
	"github.com/DeepLangAI/wcd/biz/model/wcd"
	consts2 "github.com/DeepLangAI/wcd/consts"
	wcd2 "github.com/DeepLangAI/wcd/service/wcd"
	"github.com/DeepLangAI/wcd/utils"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Segment .
// @router /v1/segment [POST]
func Segment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req wcd.SegmentReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	s := wcd2.SegmentService{}
	segmentResp, bizErr := s.HtmlSegment(ctx, req)
	if bizErr != nil {
		c.String(consts.StatusInternalServerError, bizErr.Msg)
		return
	}

	c.JSON(consts.StatusOK, segmentResp)
}

// Distill .
// @router /v1/distill [POST]
func Distill(ctx context.Context, c *app.RequestContext) {
	var err error
	var req wcd.DistillReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	s := wcd2.DistillService{}
	distillResp, bizErr := s.Distill(ctx, req)
	if bizErr != nil {
		c.String(consts.StatusInternalServerError, bizErr.Msg)
		return
	}

	c.JSON(consts.StatusOK, distillResp)
}

// WcdParse .
// @router /wcd/parse [POST]
func WcdParse(ctx context.Context, c *app.RequestContext) {
	var err error
	var req wcd.WcdParseReq

	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	s := wcd2.WcdParseService{}
	distill, bizErr := s.WcdParse(ctx, req)
	if bizErr != nil {
		if distill != nil {
			distill.Code = bizErr.Code
			distill.Msg = bizErr.Msg
			distill.Worthless = true
			distill.WorthType = consts2.WorthType_NoContent
		}
	}

	c.JSON(consts.StatusOK, distill)
}

// BaseParse .
// @router /base-parse [POST]
func BaseParse(ctx context.Context, c *app.RequestContext) {
	var err error
	var req wcd.BaseParseReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	s := wcd2.BaseParseService{}
	resp, bizErr := s.BaseParse(ctx, req)
	if bizErr != nil {
		if resp == nil {
			resp = &wcd.WcdParseResp{}
		}
		c.JSON(consts.StatusOK, wcd.WcdParseResp{
			Code:           bizErr.Code,
			Msg:            bizErr.Msg,
			URL:            req.URL,
			Text:           resp.Text,
			Images:         resp.Images,
			ReadableHTML:   resp.ReadableHTML,
			Title:          resp.Title,
			Author:         resp.Author,
			ContentSource:  resp.ContentSource,
			PubTime:        resp.PubTime,
			ModelInputStr:  resp.ModelInputStr,
			ModelResultStr: resp.ModelResultStr,
			Worthless:      true,
			WorthType:      consts2.WorthType_NoContent,
			WcdRequestID:   utils.GetCtxOperationId(ctx),
			RawHTML:        resp.RawHTML,
		})
		return
	}

	c.JSON(consts.StatusOK, resp)
}
