// Code generated by hertz generator.

package main

import (
	"github.com/DeepLangAI/go_lib/logger"
	"path/filepath"
	"strings"

	"github.com/DeepLangAI/wcd/conf"
	"github.com/DeepLangAI/wcd/dal"
	"github.com/DeepLangAI/wcd/http"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	conf.Init()
	logger.Init(conf.GetConfig().Logger)
	dal.Init()
	http.Init()

	h := server.Default(server.WithHostPorts(conf.GetConfig().Server.Port), server.WithMaxRequestBodySize(-1))
	staticFs(h)
	register(h)
	h.Spin()
}

func staticFs(h *server.Hertz) {
	// 如访问 /public/html/home.html，则返回 ./static/html/home.html
	root := conf.GetProjectPath()
	h.StaticFS("/public", &app.FS{
		Root: filepath.Join(root, "./static"),
		PathRewrite: func(ctx *app.RequestContext) []byte {
			path := string(ctx.Path())
			after, found := strings.CutPrefix(path, "/public")
			if !found {
				return []byte("")
			}
			if after == "/index.html" {
				return []byte(after)
			}
			return []byte(after)
		},
	})
}
