// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	wcd "github.com/DeepLangAI/wcd/biz/router/wcd"
	wcd_manage "github.com/DeepLangAI/wcd/biz/router/wcd_manage"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	wcd_manage.Register(r)

	wcd.Register(r)
}
