// Code generated by hertz generator.

package wcd_manage

import (
	"github.com/DeepLangAI/go_lib/middleware"
	"github.com/DeepLangAI/wcd/consts"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		middleware.TraceServerMiddleware(),
		middleware.ReqRespLogMiddleware(),
		middleware.ResponseVersionServerMiddleware(consts.VERSION),
	}
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _evalMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _execulteevalMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _site_ruleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletesiteruleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _siteruledetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _exportsiterulesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _importsiterulesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _siterulelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _prodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createsiterulefromprodMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _testingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createsiteruleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishsiteruleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatesiteruleMw() []app.HandlerFunc {
	// your code...
	return nil
}
